=== heroiclabs/hiro/schemas/01-Hiro-Reward.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "currencies": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "max": {
              "minimum": 0,
              "type": "integer"
            },
            "min": {
              "minimum": 0,
              "type": "integer"
            },
            "multiple": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "required": [
            "min"
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "energies": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "max": {
              "minimum": 0,
              "type": "integer"
            },
            "min": {
              "minimum": 0,
              "type": "integer"
            },
            "multiple": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "required": [
            "min"
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "energy_modifiers": {
      "items": {
        "properties": {
          "duration_sec": {
            "properties": {
              "max": {
                "minimum": 0,
                "type": "integer"
              },
              "min": {
                "minimum": 0,
                "type": "integer"
              },
              "multiple": {
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "min"
            ],
            "type": "object"
          },
          "id": {
            "pattern": ".{1,}",
            "type": "string"
          },
          "operator": {
            "enum": [
              "infinite",
              "set_refill_count",
              "set_refill_sec",
              "set_max_count"
            ],
            "type": "string"
          },
          "value": {
            "properties": {
              "max": {
                "minimum": 0,
                "type": "integer"
              },
              "min": {
                "minimum": 0,
                "type": "integer"
              },
              "multiple": {
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "min"
            ],
            "type": "object"
          }
        },
        "required": [
          "id",
          "operator",
          "duration_sec"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "item_sets": {
      "items": {
        "properties": {
          "max": {
            "minimum": 0,
            "type": "integer"
          },
          "max_repeats": {
            "minimum": 0,
            "type": "integer"
          },
          "min": {
            "minimum": 0,
            "type": "integer"
          },
          "multiple": {
            "minimum": 0,
            "type": "integer"
          },
          "set": {
            "items": {
              "pattern": ".{1,}",
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "min",
          "set"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "items": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "max": {
              "minimum": 0,
              "type": "integer"
            },
            "min": {
              "minimum": 0,
              "type": "integer"
            },
            "multiple": {
              "minimum": 0,
              "type": "integer"
            },
            "numeric_properties": {
              "patternProperties": {
                ".{1,}": {
                  "properties": {
                    "max": {
                      "type": "number"
                    },
                    "min": {
                      "type": "number"
                    },
                    "multiple": {
                      "minimum": 0,
                      "type": "number"
                    }
                  },
                  "required": [
                    "min"
                  ]
                }
              },
              "type": "object"
            },
            "string_properties": {
              "patternProperties": {
                ".{1,}": {
                  "properties": {
                    "options": {
                      "patternProperties": {
                        ".{1,}": {
                          "properties": {
                            "weight": {
                              "minimum": 0,
                              "type": "integer"
                            }
                          }
                        }
                      },
                      "type": "object"
                    },
                    "total_weight": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  }
                }
              },
              "type": "object"
            }
          },
          "required": [
            "min"
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "reward_modifiers": {
      "items": {
        "properties": {
          "duration_sec": {
            "properties": {
              "max": {
                "minimum": 0,
                "type": "integer"
              },
              "min": {
                "minimum": 0,
                "type": "integer"
              },
              "multiple": {
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "min"
            ],
            "type": "object"
          },
          "id": {
            "pattern": ".{1,}",
            "type": "string"
          },
          "operator": {
            "enum": [
              "multiplier",
              "addition"
            ],
            "type": "string"
          },
          "type": {
            "enum": [
              "currency",
              "item"
            ],
            "type": "string"
          },
          "value": {
            "properties": {
              "max": {
                "minimum": 0,
                "type": "integer"
              },
              "min": {
                "minimum": 0,
                "type": "integer"
              },
              "multiple": {
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "min"
            ],
            "type": "object"
          }
        },
        "required": [
          "id",
          "type",
          "operator",
          "value",
          "duration_sec"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "weight": {
      "minimum": 0,
      "type": "integer"
    }
  },
  "type": "object"
}

=== heroiclabs/hiro/configuration/_01-Hiro-Reward.json
{
  "items": {
    "item1": {
      "min": 2,
      "max": 2,
      "multiple": 1
    },
    "item2": {
      "min": 10,
      "max": 100,
      "multiple": 5
    }
  },
  "item_sets": [
    {
      "min": 1,
      "max": 10,
      "multiple": 1,
      "max_repeats": 0,
      "set": [ "set1", "set2" ]
    }
  ],
  "currencies": {
    "currency1": {
      "min": 1,
      "max": 10,
      "multiple": 1
    },
    "currency2": {
      "min": 10,
      "max": 100,
      "multiple": 5
    }
  },
  "energies": {
    "energy1": {
      "min": 1,
      "max": 10,
      "multiple": 1
    },
    "energy2": {
      "min": 10,
      "max": 100,
      "multiple": 5
    }
  },
  "energy_modifiers": [
    {
      "id": "id1",
      "operator": "infinite",
      "duration_sec": {
        "min": 30,
        "max": 60,
        "multiple": 5
      }
    },
    {
      "id": "id2",
      "operator": "infinite",
      "duration_sec": {
        "min": 1,
        "max": 10,
        "multiple": 1
      }
    }
  ],
  "reward_modifiers": [
    {
      "id": "id1",
      "type": "currency",
      "operator": "multiplier",
      "value": {
        "min": 1,
        "max": 3,
        "multiple": 1
      },
      "duration_sec": {
        "min": 30,
        "max": 60,
        "multiple": 5
      }
    },
    {
      "id": "id2",
      "type": "item",
      "operator": "addition",
      "value": {
        "min": 10,
        "max": 50,
        "multiple": 10
      },
      "duration_sec": {
        "min": 30,
        "max": 60,
        "multiple": 5
      }
    }
  ],
  "weight": 1
}
