=== heroiclabs/hiro/schemas/01-Hiro-Base.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "rate_app_smtp_addr": {
      "pattern": ".{1,}",
      "title": "rate_app_smtp_addr",
      "type": "string"
    },
    "rate_app_smtp_email_from": {
      "format": "email",
      "title": "rate_app_smtp_email_from",
      "type": "string"
    },
    "rate_app_smtp_email_from_name": {
      "pattern": ".{1,}",
      "title": "rate_app_smtp_email_from_name",
      "type": "string"
    },
    "rate_app_smtp_email_subject": {
      "pattern": ".{1,}",
      "title": "rate_app_smtp_email_subject",
      "type": "string"
    },
    "rate_app_smtp_email_to": {
      "format": "email",
      "title": "rate_app_smtp_email_to",
      "type": "string"
    },
    "rate_app_smtp_password": {
      "pattern": ".{1,}",
      "title": "rate_app_smtp_password",
      "type": "string"
    },
    "rate_app_smtp_port": {
      "maximum": 65535,
      "minimum": 1,
      "title": "rate_app_smtp_port",
      "type": "number"
    },
    "rate_app_smtp_username": {
      "pattern": ".{1,}",
      "title": "rate_app_smtp_username",
      "type": "string"
    },
    "rate_app_template": {
      "pattern": ".{1,}",
      "title": "rate_app_template",
      "type": "string"
    }
  },
  "type": "object"
}

=== heroiclabs/hiro/configuration/03-Hiro-Base.json
{
    "rate_app_smtp_addr": "smtp.gmail.com",
    "rate_app_smtp_username": "email@domain.com",
    "rate_app_smtp_password": "password",
    "rate_app_smtp_email_from": "gamename-server@mygamecompany.com",
    "rate_app_smtp_email_from_name": "My Game Company",
    "rate_app_smtp_email_subject": "RateApp Feedback",
    "rate_app_smtp_email_to": "gamename-rateapp@mygamecompany.com",
    "rate_app_smtp_port": 12345,
    "rate_app_template": "<template>"
}
