=== heroiclabs/hiro/schemas/03-Hiro-Rewards.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "guaranteed": {
      "title": "guaranteed",
      "$ref": "Hiro-Reward"
    },
    "weighted": {
      "title": "weighted",
      "type": "array",
      "items": {
        "$ref": "Hiro-Reward"
      }
    },
    "max_rolls": {
      "type": "number",
      "title": "max_rolls",
      "minimum": 0
    },
    "total_weight": {
      "type": "number",
      "title": "total_weight",
      "minimum": 0
    }
  },
  "type": "object"
}

=== heroiclabs/hiro/definitions/_02-Hiro-Rewards.json
{
  "guaranteed": {
    "items": [
      {
        "key": "item1",
        "value": {
          "max": 2,
          "min": 2,
          "multiple": 1
        }
      },
      {
        "key": "item2",
        "value": {
          "max": 100,
          "min": 10,
          "multiple": 5
        }
      }
    ]
  },
  "weighted": [
    {
      "currencies": [
        {
          "key": "currency1",
          "value": {
            "max": 200,
            "min": 100
          }
        }
      ],
      "weight": 5
    }
  ],
  "max_rolls": 2,
  "total_weight": 5
}

=== heroiclabs/hiro/configuration/_02-Hiro-Rewards.json
{
  "guaranteed": {
    "items": {
      "item1": {
        "min": 2,
        "max": 2,
        "multiple": 1
      },
      "item2": {
        "min": 10,
        "max": 100,
        "multiple": 5
      }
    }
  },
  "weighted": [
    {
      "currencies": {
        "currency1": {
          "min": 100,
          "max": 200
        }
      },
      "weight": 5
    }
  ],
  "max_rolls": 2,
  "total_weight": 5
}
