=== heroiclabs/hiro/schemas/09-Hiro-Economy.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "donations": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "additional_properties": {
              "patternProperties": {
                ".{1,}": {
                  "type": "string"
                }
              },
              "type": "object"
            },
            "contributor_reward": {
              "$ref": "Hiro-Rewards"
            },
            "cost": {
              "properties": {
                "currencies": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                },
                "items": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "count": {
              "minimum": 0,
              "type": "integer"
            },
            "description": {
              "pattern": ".*",
              "type": "string"
            },
            "max_count": {
              "minimum": 0,
              "type": "integer"
            },
            "name": {
              "pattern": ".{1,}",
              "type": "string"
            },
            "recipient_reward": {
              "$ref": "Hiro-Rewards"
            },
            "user_contribution_max_count": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "required": [
            "name",
            "max_count"
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "initialize_user": {
      "properties": {
        "currencies": {
          "patternProperties": {
            ".{1,}": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "type": "object"
        },
        "items": {
          "patternProperties": {
            ".{1,}": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "placements": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "additional_properties": {
              "patternProperties": {
                ".{1,}": {
                  "type": "string"
                }
              },
              "type": "object"
            },
            "reward": {
              "$ref": "Hiro-Rewards"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "store_items": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "additional_properties": {
              "patternProperties": {
                ".{1,}": {
                  "type": "string"
                }
              },
              "type": "object"
            },
            "category": {
              "pattern": ".{1,}",
              "type": "string"
            },
            "cost": {
              "properties": {
                "currencies": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                },
                "sku": {
                  "pattern": ".{1,}",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "description": {
              "pattern": ".*",
              "type": "string"
            },
            "disabled": {
              "type": "boolean"
            },
            "unavailable": {
              "type": "boolean"
            },
            "name": {
              "pattern": ".{1,}",
              "type": "string"
            },
            "reward": {
              "$ref": "Hiro-Rewards"
            }
          },
          "required": [
            "name"
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "allow_fake_receipts": {
      "type": "boolean"
    }
  },
  "type": "object"
}

=== heroiclabs/hiro/definitions/09-Hiro-Economy.json
{
    "initialize_user": {
      "currencies": {
        "currency1": 100,
        "currency2": 200
      },
      "items": {
        "item1": 5,
        "item2": 10
      }
    },
    "donations": {
      "donation1": {
        "cost": {
          "currencies": {
            "currency1": 100,
            "currency2": 200
          },
          "items": {
            "item1": 5,
            "item2": 10
          }
        },
        "count": 0,
        "description": "description1",
        "duration_sec": 3600,
        "max_count": 10,
        "name": "name1",
        "recipient_reward": {},
        "contributor_reward": {},
        "user_contribution_max_count": 2,
        "additional_properties": {
          "key1": "value1"
        }
      }
    },
    "store_items": {
      "store_item1": {
        "category": "category1",
        "cost": {
          "currencies": {
            "currency1": 50,
            "currency2": 75
          },
          "sku": "some_sku_here"
        },
        "description": "description1",
        "name": "name1",
        "reward": {},
        "additional_properties": {
          "key1": "value1"
        }
      }
    },
    "placements": {
      "placement1": {
        "reward": {},
        "additional_properties": {
          "key1": "value1"
        }
      }
    }
}
