=== heroiclabs/hiro/schemas/11-Hiro-Unlockables.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "active_slots": {
      "minimum": 0,
      "type": "integer"
    },
    "max_active_slots": {
      "minimum": 0,
      "type": "integer"
    },
    "max_queued_unlocks": {
      "minimum": 0,
      "type": "integer"
    },
    "slot_cost": {
      "properties": {
        "currencies": {
          "patternProperties": {
            ".{1,}": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "type": "object"
        },
        "items": {
          "patternProperties": {
            ".{1,}": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "slots": {
      "minimum": 0,
      "type": "integer"
    },
    "unlockables": {
      "patternProperties": {
        ".{1,}": {
          "properties": {
            "additional_properties": {
              "patternProperties": {
                ".{1,}": {
                  "type": "string"
                }
              },
              "type": "object"
            },
            "category": {
              "pattern": ".{1,}",
              "type": "string"
            },
            "cost": {
              "properties": {
                "currencies": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                },
                "items": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "cost_unit_time_sec": {
              "minimum": 0,
              "type": "integer"
            },
            "description": {
              "pattern": ".*",
              "type": "string"
            },
            "name": {
              "pattern": ".{1,}",
              "type": "string"
            },
            "probability": {
              "minimum": 0,
              "type": "integer"
            },
            "reward": {
              "$ref": "Hiro-Rewards"
            },
            "start_cost": {
              "properties": {
                "currencies": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                },
                "items": {
                  "patternProperties": {
                    ".{1,}": {
                      "minimum": 0,
                      "type": "integer"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "wait_time_sec": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "required": [
            "probability",
            "name"
          ],
          "type": "object"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}

=== heroiclabs/hiro/definitions/11-Hiro-Unlockables.json
{
    "active_slots": 1,
    "max_active_slots": 3,
    "slots": 5,
    "slot_cost": {
      "items": {
        "item1": 5,
        "item2": 10
      },
      "currencies": {
        "currency1": 100,
        "currency2": 200
      }
    },
    "unlockables": {
      "id1": {
        "probability": 50,
        "category": "category1",
        "cost": {
          "items": {
            "item1": 5,
            "item2": 10
          },
          "currencies": {
            "currency1": 100,
            "currency2": 200
          }
        },
        "cost_unit_time_sec": 1,
        "description": "description1",
        "name": "name1",
        "start_cost": {
          "items": {
            "item1": 5,
            "item2": 10
          },
          "currencies": {
            "currency1": 100,
            "currency2": 200
          }
        },
        "reward": {
          "guaranteed": {
            "energies": {
              "energy1": {
                "min": 10,
                "max": 10
              }
            }
          }
        },
        "wait_time_sec": 60,
        "additional_properties": {
          "key1": "value1"
        }
      }
    }
}
